app:
  jwt:
    secret: ZWxvZWxvMTEyM2Fzc2Rm

spring:
  application:
    name: zuul

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

users-ms-context: /users-ms/
api:
  login:
    url: ${users-ms-context}login
  registration:
    url: ${users-ms-context}users/create
  h2-console:
    url: ${users-ms-context}h2-console/**